import { Link }   from 'react-router-dom'
import { motion } from 'framer-motion'
import {
  FileText, Star, Briefcase, BarChart2,
  Linkedin, MessageSquare, Target, ArrowRight,
} from 'lucide-react'
import { Button } from '@/components/ui'
import { ROUTES } from '@/config/routes'

const services = [
  {
    icon: <Star size={24} />,
    color: 'bg-violet-100 text-violet-600',
    name: 'Evidence Bank',
    tagline: 'Your career story, structured.',
    body: `Log achievements, projects, certifications, and skills. Our AI structures them using the STAR
    method so every bullet is interview-ready. Import from LinkedIn or add manually. Entries are searchable,
    taggable, and reusable across every CV you create.`,
    included: 'Free plan',
  },
  {
    icon: <FileText size={24} />,
    color: 'bg-brand-100 text-brand-600',
    name: 'CV Writing',
    tagline: 'Specialist-reviewed, ATS-optimised.',
    body: `Our CV writers create tailored CVs pulling directly from your Evidence Bank. Each CV is reviewed
    by a human specialist — not just generated by AI — and comes with an ATS score before you download.
    Word and PDF formats included. Unlimited revisions.`,
    included: 'Launch & above',
  },
  {
    icon: <Briefcase size={24} />,
    color: 'bg-emerald-100 text-emerald-600',
    name: 'Application Tracker',
    tagline: 'Know exactly where every application stands.',
    body: `Kanban-style tracker to manage every job from Saved to Offer. Add job descriptions to get an
    AI role-fit score before applying. Set deadlines, write notes, track interview rounds. You approve
    every application — Campus to Corporate never applies on your behalf without your say-so.`,
    included: 'Free plan',
  },
  {
    icon: <Target size={24} />,
    color: 'bg-amber-100 text-amber-700',
    name: 'Role-Fit Scoring',
    tagline: 'Apply smarter, not just more.',
    body: `Paste a job description and instantly see how well your profile matches — broken down by skills,
    experience, and seniority level. Understand exactly what gaps exist before you apply, and use the
    breakdown to tailor your CV and cover letter.`,
    included: 'Launch & above',
  },
  {
    icon: <Linkedin size={24} />,
    color: 'bg-blue-100 text-blue-600',
    name: 'LinkedIn Optimisation',
    tagline: 'Get found by the right recruiters.',
    body: `A specialist rewrites your LinkedIn headline, summary, and experience section using keywords
    that surface your profile in recruiter searches. Based on your target role and sector. Delivered
    within 24 hours with a before/after comparison.`,
    included: 'One-off service',
  },
  {
    icon: <MessageSquare size={24} />,
    color: 'bg-rose-100 text-rose-600',
    name: 'Interview Preparation',
    tagline: 'Walk in confident. Walk out with the offer.',
    body: `Tailored to the company and role you're interviewing for. Includes likely questions, structured
    answers from your Evidence Bank, STAR method practice, and a 60-minute coaching session with a
    career specialist.`,
    included: 'Momentum & one-off',
  },
  {
    icon: <BarChart2 size={24} />,
    color: 'bg-teal-100 text-teal-600',
    name: 'Career Analytics',
    tagline: "See what's working and what isn't.",
    body: `Real-time dashboard showing your application funnel — response rate, interview conversion,
    time-to-offer, and sector breakdown. Use the data to refine your approach. Know which roles are
    worth pursuing and which CVs are converting.`,
    included: 'All plans',
  },
  {
    icon: <Target size={24} />,
    color: 'bg-orange-100 text-orange-600',
    name: 'Salary Negotiation',
    tagline: "Don't leave money on the table.",
    body: `When you have an offer, our specialists help you evaluate it against UK market data, prepare
    counter-offer scripts, and practise the conversation. Most clients recover the cost of the session
    in the first month of their new role.`,
    included: 'One-off service',
  },
]

export default function ServicesPage() {
  return (
    <>
      {/* Hero */}
      <section className="section-padding pt-24 pb-16 bg-gradient-to-b from-slate-50 to-white text-center">
        <div className="container-xl max-w-2xl mx-auto">
          <p className="eyebrow mb-4">Services</p>
          <h1 className="text-5xl font-display font-extrabold text-slate-900 mb-5">
            Everything your job search needs
          </h1>
          <p className="text-xl text-slate-500">
            AI tools, human specialists, and a structured process — all in one platform.
          </p>
        </div>
      </section>

      {/* Service cards */}
      <section className="section-padding bg-white">
        <div className="container-xl">
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {services.map(({ icon, color, name, tagline, body, included }, i) => (
              <motion.div
                key={name}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: (i % 3) * 0.1, duration: 0.4 }}
                className="bg-white rounded-2xl border border-slate-200 p-6 flex flex-col hover:border-brand-200 hover:shadow-brand transition-all duration-200"
              >
                <div className={`w-12 h-12 rounded-2xl flex items-center justify-center mb-4 ${color}`}>
                  {icon}
                </div>
                <div className="flex items-start justify-between gap-2 mb-1">
                  <h3 className="font-display font-bold text-slate-900">{name}</h3>
                  <span className="text-xs bg-slate-100 text-slate-500 px-2 py-0.5 rounded-full shrink-0">
                    {included}
                  </span>
                </div>
                <p className="text-sm text-brand-600 font-medium mb-3">{tagline}</p>
                <p className="text-sm text-slate-500 leading-relaxed flex-1">{body}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Comparison note */}
      <section className="section-padding bg-slate-50">
        <div className="container-xl max-w-3xl mx-auto text-center">
          <h2 className="text-3xl font-display font-bold text-slate-900 mb-4">
            Not sure which plan covers what you need?
          </h2>
          <p className="text-slate-500 mb-8">
            The Explore plan is free and includes the Evidence Bank and application tracker.
            Launch and Momentum add AI CV writing and specialist reviews. Individual services
            can be purchased without a subscription.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link to={ROUTES.PRICING}>
              <Button variant="primary" iconRight={<ArrowRight size={16} />}>View pricing</Button>
            </Link>
            <Link to={ROUTES.REGISTER}>
              <Button variant="secondary">Start for free</Button>
            </Link>
          </div>
        </div>
      </section>
    </>
  )
}
